### ISSUE TITLE
Set maxRows in viewDidLoad

### ISSUE THREAD

**Issue by Jan-E** [felipowsky/FYComboBox#1]
@felipowsky Your example is a bit flawed. The lines after https://github.com/felipowsky/FYComboBox/blob/master/FYComboBoxExample/FYComboBoxExample/ViewController.m#L16 should be

    self.languages = @[@"Objective-C", @"Swift", @"Python", @"C++", @"C"];
    self.languagesComboBox.maxRows = self.languages.count;
    
    self.colors = @[@"Red", @"Orange", @"Green", @"Blue", @"Yellow", @"Black", @"White", @"Gray"];
    self.colorsComboBox.maxRows = self.colors.count;

Without those extra lines the number of displayed lines will be the default (3) for languages or the number in the main storyboard for colors (2).

Otherwise, FYComboBox is a fine example of a ComboBox on a iPad. Thank you.

PS. Sorry, no PR. My fork is hevily changed while testing it.

**Comment by felipowsky** [comment]
Thanks for your contribution @Jan-E.
Maybe the idea behind `maxRows` is a little confusing because of its name.
The idea is to have an option to configure the maximum visible rows when displaying the combo box.
If you use a `maxRow` lower than the number of rows in your combo you can use the scroll to reach the hidden options.
Maybe I should rename this property to `maxVisibleRows`.
What do you think?
